### PR TITLE
Change NQP to Not Quite Paradise

### PR DESCRIPTION
**Pull request by lizmat**
Inspired by https://www.reddit.com/r/rakulang/comments/jmvnf2/renaming_nqp/

### CODE REVIEW

**Comment by ugexe** [comment]
I never understood the desire to rename NQP... "Not Quite Perl" is as accurate a description now as it was 10 years ago.

**Comment by raiph** [comment]
For @ugexe, @vrurg, @coke, and anyone else who agrees or disagrees with @ugexe's earlier comment:

> "Not Quite Perl" is as accurate a description now as it was 10 years ago.

I agree.

As you'll see if you read my comment, I did not suggest in my reddit post that NQP stops being Not Quite Perl.

**Comment by lizmat** [comment]
@raiph having "NQP" being a Junction, is, in my mind almost just as bad as having "Raku" being an alias for Perl 6.  But the feelings are clear.  And it's not a big beef of mine, I also just wanted to throw it out there.  And am throwing it back in again now.

**Comment by xfix** [comment]
Not Quite Perl is a fine name in my opinion, I don't think Not Quite Perl should be renamed (other than maybe NQP, as in, removing acronym entirely). Just because the language was renamed from Perl 6 to Raku doesn't mean NQP has to change.

**Pull request closed without merging**
